# Generated by Django 4.2.1 on 2023-06-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_unique_together_alter_cart_index_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='check_out',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
