# Generated by Django 4.2.1 on 2023-06-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='check_out',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
