# Generated by Django 4.2.1 on 2023-06-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('games', '0022_alter_wishlist_unique_together'),
        ('cart', '0006_alter_cart_check_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='game',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='timestampedmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('check_out', models.BooleanField(blank=True, default=False, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_cart', to='cart.cart')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_game', to='games.game')),
            ],
            options={
                'unique_together': {('game', 'cart')},
                'index_together': {('game', 'cart')},
            },
        ),
    ]
