# Generated by Django 4.2.1 on 2023-06-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='check_out',
        ),
        migrations.AddField(
            model_name='cart',
            name='check_out',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
