# Generated by Django 4.2.1 on 2023-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_cartitem_check_out_cart_check_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='check_out',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='check_out',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
