# Generated by Django 4.2.1 on 2023-06-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='photos/character/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sale', models.IntegerField(blank=True, null=True)),
                ('trend', models.BooleanField()),
                ('logo', models.ImageField(upload_to='Photos/logo/%y/%m/%d')),
                ('banner', models.ImageField(upload_to='Photos/banner/%y/%m/%d')),
                ('BannerLogo', models.ImageField(upload_to='Photos/bannerLogo/%y/%m/%d')),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('intialRelease', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=300, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('developer', models.CharField(blank=True, max_length=300, null=True)),
                ('features', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.category')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='games.character')),
            ],
            bases=('core.timestampedmodel',),
        ),
    ]
