# Generated by Django 4.2.2 on 2023-06-24 00:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('details', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(100), django.core.validators.MaxLengthValidator(150)])),
                ('image', models.FileField(upload_to='photos/character/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])])),
                ('slug', models.SlugField(blank=True, help_text='NEVER EVER EDIT', null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='Photos/gallery/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Free'), (2, 'Paid')], null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('trend', models.BooleanField(blank=True, null=True)),
                ('logo', models.FileField(upload_to='Photos/logo/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])])),
                ('banner', models.FileField(upload_to='Photos/banner/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])])),
                ('popular', models.BooleanField(blank=True, null=True)),
                ('bannerLogo', models.FileField(upload_to='Photos/bannerLogo/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])])),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('intialRelease', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=300, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('developer', models.CharField(blank=True, max_length=300, null=True)),
                ('features', models.CharField(blank=True, max_length=300, null=True)),
                ('views', models.IntegerField(blank=True, help_text='DON`T EDIT', null=True)),
                ('slug', models.SlugField(blank=True, help_text='NEVER EVER EDIT', null=True)),
                ('categories', models.ManyToManyField(to='games.category')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='games.character')),
            ],
        ),
    ]
