# Generated by Django 4.2.1 on 2023-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='details2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
