# Generated by Django 4.2.1 on 2023-06-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.RemoveField(
            model_name='game',
            name='character',
        ),
        migrations.AddField(
            model_name='category',
            name='Game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='games.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='games.game'),
            preserve_default=False,
        ),
    ]
