# Generated by Django 4.2.1 on 2023-06-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('games', '0002_remove_game_category_remove_game_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('image', models.ImageField(upload_to='Photos/gallery/%y/%m/%d')),
            ],
            bases=('core.timestampedmodel',),
        ),
    ]
