# Generated by Django 4.2.1 on 2023-06-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_sale_game_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='views',
            field=models.IntegerField(blank=True, help_text='DON`T EDIT !', null=True),
        ),
    ]
