# Generated by Django 4.2.1 on 2023-06-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Free'), (2, 'Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='trend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='views',
            field=models.IntegerField(blank=True, help_text='DON`T EDIT', null=True),
        ),
    ]
