# Generated by Django 4.2.1 on 2023-06-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_category_game_remove_character_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='categories',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(to='games.category'),
        ),
    ]
