# Generated by Django 4.2.1 on 2023-06-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_game_categories_game_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='popular',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
