# Generated by Django 4.2.1 on 2023-06-19 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_character_image_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(upload_to='photos/character/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='Photos/gallery/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.ImageField(upload_to='Photos/banner/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='game',
            name='bannerLogo',
            field=models.ImageField(upload_to='Photos/bannerLogo/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(upload_to='Photos/logo/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg', 'avif', 'jpeg'])]),
        ),
    ]
