# Generated by Django 4.2.1 on 2023-06-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_character_image_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, help_text='NEVER EVER EDIT', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
