# Generated by Django 4.2.1 on 2023-06-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_slug_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, help_text='NEVER EVER EDIT', null=True),
        ),
    ]
