# Generated by Django 4.2.1 on 2023-06-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
