# Generated by Django 4.2.1 on 2023-06-21 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0020_alter_wishlist_game_alter_wishlist_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wishlist',
            name='games_wishl_user_id_32a415_idx',
        ),
        migrations.AlterIndexTogether(
            name='wishlist',
            index_together={('user', 'game')},
        ),
    ]
