# Generated by Django 4.2.1 on 2023-06-21 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0021_remove_wishlist_games_wishl_user_id_32a415_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'game')},
        ),
    ]
