# Generated by Django 4.2.1 on 2023-06-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
